# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12bfa6139cdf2af88a442d45a3935d342d30b7b90673c2cffa466182fbfe5721bd0895674d0f6d4bb0ce3c6433187264b1d3f03e59449564b64af29925703da3

test:
  secret_key_base: f551352fd421e10044aaa6b5f207ef24f4643affd2c8a02e9e8e11fe974a56e8fec466b90b5b278dd706372a25500a2a9fb5dc20eb6779258e5957419230ef22

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
